POST http://localhost:3003/users
Content-Type: application/json

{
    "name" : "Joselice",
    "email" : "joselice@labenu.com",
    "password" : "12345"
}

###

GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name" : "GS1250",
    "price" : 110000,
    "image_url" : "https://cdn.motor1.com/images/mgl/38wX6/s1/4x3/bmw-r-1250-gs.webp"
}

###

GET http://localhost:3003/products
Content-Type: application/json

###

POST http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id" : "0.435787392683314",
    "product_id" : "0.9592330036854957",
    "quantity" : 5
}

###

GET http://localhost:3003/users/:user_id/purchases
Content-Type: application/json

{
"user_id" : "0.435787392683314"
}