POST http://localhost:3003/users
Content-Type: application/json

{
    "name" : "Joselice",
    "email" : "joselice@labenu.com",
    "password" : "12345"
}

###

GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name" : "Maserati",
    "price" : 100000000,
    "image_url" : "https://image1.mobiauto.com.br/images/api/images/v1.0/43157426/transform/"
}